@startuml
class DoubleCpu {
- ArrayList<PersonRequest> inWantOuts
- ArrayList<PersonRequest> outWantIns
- ArrayList<PersonRequest> specialNeeds
- ArrayList<PersonRequest> seeRequests
- ArrayList<PersonRequest> personIns
- DoubleReQueue requestQueue
- DoublEleThread elevator
- int isAorB
- int maxNum
- int exchange
- int dir
- boolean startORstop
- boolean ifOpen
- int now
+ void check()
+ boolean checkExchange()
+ boolean downContinueDir()
+ void getToDir()
+ boolean upCome()
+ ArrayList<PersonRequest> getQueRequests()
+ ArrayList<PersonRequest> getInWantOuts()
+ ArrayList<PersonRequest> getOutWantIns()
+ ArrayList<PersonRequest> getSpecialNeeds()
+ int getDir()
+ boolean isIfOpen()
+ boolean isStartORstop()
}


@enduml