@startuml
class DoublEleThread {
- DoubleReQueue elevatorQueue
- int id
- int speedTime
- int maxNum
- int exchange
- int isAorB
- DoubleCpu elCpu
- ArrayList<PersonRequest> inElevators
- boolean isOpen
- int nowFloor
- int eleDir
+ void run()
+ void tranAway()
+ void outAndin()
+ void moveOneFloor()
+ void closeDoor()
+ void openDoor()
+ boolean getGlag()
+ void trySleep(long)
+ void Arrive()
+ void removeRqs(PersonRequest)
+ void outAperson(PersonRequest)
+ void inOnePer(PersonRequest)
+ int getNowFloor()
+ int getInNum()
+ ArrayList<PersonRequest> getInElevators()
}




Thread <|-- DoublEleThread
@enduml