@startuml
class Dispatcher {
- String workerId
- String workerName
- ArrayList<String> roomStateTable
- Cleaner cleaner
- boolean isCleanOperation
+ String getWorkerId()
+ String getWorkerName()
+ void setCleaner(Cleaner)
- int findSpareRoom()
- boolean isCleanOperation()
- boolean isCheckOutOperation()
+ int checkIn()
+ void checkOut(int)
+ void clean(int)
- void arrange2clean(int)
- void finishClean(int)
}


@enduml