@startuml
class DoubleReQueue {
- int id
- boolean isEnd
- int balance
- int exchange
- int tranDownUp
- int speedTime
- boolean canChange
- ArrayList<PersonRequest> upRequests
- ArrayList<PersonRequest> downRequests
- DoublEleThread eleDownA
- DoublEleThread eleUpB
- int maxNum
- int numdA
- int numuB
+ void makeEle(DoublEleThread,DoublEleThread)
+ boolean getUpbGlag()
+ void removeUp(PersonRequest)
+ void addRequest(Request)
+ ArrayList<PersonRequest> getUps()
+ int getSize()
+ int getBalance()
+ int getSpeedTime()
+ void writeCanChange(boolean)
+ boolean isCanChange()
+ boolean isEnd()
+ boolean isEmpty()
+ void setEnd(boolean)
+ void writeSomething(int,int)
+ void setTranID(int)
+ int getTranDownUp()
+ int getAnotherN(int)
+ boolean getDownaGlag()
+ ArrayList<PersonRequest> getDowns()
+ void removeDown(PersonRequest)
}




ReQueue <|.. DoubleReQueue
@enduml