@startuml

class Poly {
- ArrayList<Mono> monos
}


class Mono {

}

Mono --> Poly:monos存在于Poly
expNeiPoly ..> Mono:Mono可能存在exPoly
newMonos --> expNeiPoly
sign --> Mono
C --> Mono
E --> Mono
haveExp --> Mono
true --> haveExp
false --> haveExp
expNeiPoly --> true
@enduml